name              "bashrc"
maintainer        "Fletcher Nichol"
maintainer_email  "fnichol@nichol.ca"
license           "Apache 2.0"
description       "A resource to install a bash profile from http://github.com/fnichol/bashrc."
version           "1.99.1"

supports "centos"
supports "mac_os_x"
supports "ubuntu"
supports "suse"
